spring.datasource.url= jdbc:postgresql://localhost:5432/telegram_bot_remainder_DB
spring.datasource.username=telegram_user_for_remainder
spring.datasource.password=user123
telegram.bot.token=8781960633:AAG23VD5q1UzcSDKR6ZCrHO7n2vab76JXOM

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml



